// server/src/config/ges-config.js
export const GES_DATOS_PREDEFINIDOS = {
    "Caídas al mismo nivel": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: 1, // Crítico
            EMOMP: 2, // Recomendado
            EMOA: 2, // Recomendado
            AUD: 2, // Recomendado
            ESP: 2, // Recomendado
            OPT: 2, // Recomendado
            VIS: 2, // Recomendado
            ECG: 2, // Recomendado
            RXC: 2, // Recomendado
            PSM: 2, // Recomendado
            PST: 2, // Recomendado
            GLI: 2, // Recomendado
            CH: 2, // Recomendado
            PL: 2, // Recomendado
            PAS:2, // Recomendado
            PE: 2, // Recomendado
            PSP: 2, // Recomendado
            TGO: 2, // Recomendado
            TGP: 2, // Recomendado
            TRI: 2, // Recomendado
            CRE: 2, // Recomendado
            BUN: 2, // Recomendado
            T4L: 2, // Recomendado
            TSH: 2, // Recomendado
            BRU: 2, // Recomendado
            PO: 2, // Recomendado
            TOX: 2, // Recomendado
            LEP: 2, // Recomendado
            COP: 2, // Recomendado
            FRO: 2, // Recomendado
            KOH: 2, // Recomendado
            COLI: 2, // Recomendado
            VH: 2, // Recomendado
            VT: 2, // Recomendado
            VFA: 2 // Recomendado
        },
        elementosProteccion: "Calzado de seguridad antideslizante, señalización de áreas, cintas antideslizantes",
        medidasIntervencion: {
            eliminacion: "Eliminación: Reparar superficies irregulares",
            sustitucion: "Sustitución: Cambiar pisos por materiales antideslizantes",
            controlesIngenieria: "Controles de ingeniería: Instalación de barandas y superficies antideslizantes",
            controlesAdministrativos: "Controles administrativos: Capacitación en autocuidado"
        }
    },

    "Caídas de altura": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMOA: 1, // Crítico/Obligatorio
            VIS: 1,  // Crítico para la tarea
            PSM: 2,  // Recomendado
            ECG: 2,
            GLI: 2,
            PSP: 2
            // Se omiten otros que pueden ser menos directos para el paquete básico
        },
        elementosProteccion: "Arnés de seguridad, línea de vida, casco con barbuquejo, puntos de anclaje certificados",
        medidasIntervencion: {
            eliminacion: "Eliminación: Realizar trabajos a nivel del suelo cuando sea posible",
            sustitucion: "Sustitución: Uso de plataformas elevadoras",
            controlesIngenieria: "Controles de ingeniería: Instalación de barandas permanentes",
            controlesAdministrativos: "Controles administrativos: Permisos de trabajo en altura"
        }
    },

    "Posibilidad de atrapamiento": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Guardas de seguridad, dispositivos de parada de emergencia, ropa ajustada",
        medidasIntervencion: {
            eliminacion: "Eliminación: Automatización de procesos peligrosos",
            sustitucion: "Sustitución: Equipos con sistemas de seguridad integrados",
            controlesIngenieria: "Controles de ingeniería: Instalación de guardas y sensores",
            controlesAdministrativos: "Controles administrativos: Procedimientos de bloqueo y etiquetado"
        }
    },

    "Posibilidad de ser golpeado por objetos que caen o en movimiento": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Casco de seguridad, calzado con puntera, señalización de áreas",
        medidasIntervencion: {
            eliminacion: "Eliminación: Rediseño de áreas de trabajo",
            sustitucion: "Sustitución: Implementar sistemas automatizados",
            controlesIngenieria: "Controles de ingeniería: Barreras físicas y redes de seguridad",
            controlesAdministrativos: "Controles administrativos: Señalización y demarcación de áreas"
        }
    },

    "Posibilidad de proyección de partículas o fluidos a presión": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Gafas de seguridad, careta facial, ropa de protección",
        medidasIntervencion: {
            eliminacion: "Eliminación: Cambio de procesos que generen proyecciones",
            sustitucion: "Sustitución: Uso de sistemas cerrados",
            controlesIngenieria: "Controles de ingeniería: Pantallas de protección",
            controlesAdministrativos: "Controles administrativos: Procedimientos de trabajo seguro"
        }
    },

    "Posibilidad de perforación o de punzonamiento": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Guantes anticorte, calzado de seguridad, mangas de protección",
        medidasIntervencion: {
            eliminacion: "Eliminación: Automatización de procesos con riesgo de perforación",
            sustitucion: "Sustitución: Herramientas con protecciones integradas",
            controlesIngenieria: "Controles de ingeniería: Guardas de seguridad",
            controlesAdministrativos: "Controles administrativos: Capacitación en uso seguro de herramientas"
        }
    },

    "Posibilidad de corte o seccionamiento": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Guantes anticorte, mangas de protección, delantal de seguridad",
        medidasIntervencion: {
            eliminacion: "Eliminación: Automatización de procesos de corte",
            sustitucion: "Sustitución: Herramientas con sistemas de seguridad",
            controlesIngenieria: "Controles de ingeniería: Guardas y dispositivos de protección",
            controlesAdministrativos: "Controles administrativos: Procedimientos de trabajo seguro"
        }
    },





    "Alta tensión debido a instalaciones eléctricas locativas y estáticas": {
        consecuencias: "Quemaduras fibrilación ventricular shock eléctrico",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: false,
            EMOMP: false,
            EMOA: true,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: true,
            RXC: true,
            PSM: false,
            PST: true,
            GLI: true,
            CH: true,
            PL: false,
            PAS:false,
            PE: false,
            PSP: true,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Guantes dieléctricos, botas dielécricas, traje arc flash, careta",
        medidasIntervencion: {
            eliminacion: "Eliminación: Desenergización completa",
            sustitucion: "Sustitución: Sistemas de bajo voltaje",
            controlesIngenieria: "Controles de ingeniería: Sistemas de bloqueo",
            controlesAdministrativos: "Controles administrativos: Procedimientos específicos"
        }
    },

    "Media tensión debido a instalaciones eléctricas locativas y estáticas": {
        consecuencias: "Quemaduras fibrilación ventricular shock eléctrico",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: false,
            EMOMP: false,
            EMOA: true,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: true,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: true,
            CH: true,
            PL: false,
            PAS:false,
            PE: false,
            PSP: true,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Guantes dieléctricos clase adecuada, calzado dieléctrico",
        medidasIntervencion: {
            eliminacion: "Eliminación: Reubicación de instalaciones",
            sustitucion: "Sustitución: Actualización de sistemas eléctricos",
            controlesIngenieria: "Controles de ingeniería: Aislamiento y señalización",
            controlesAdministrativos: "Controles administrativos: Permisos de trabajo"
        }
    },

    "Baja tensión debido a instalaciones eléctricas locativas y estáticas": {
        consecuencias: "Quemaduras fibrilación ventricular shock eléctrico",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: false,
            EMOMP: false,
            EMOA: true,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: true,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: true,
            CH: true,
            PL: false,
            PAS:false,
            PE: false,
            PSP: true,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Guantes dieléctricos, herramientas aisladas",
        medidasIntervencion: {
            eliminacion: "Eliminación: Reemplazo de instalaciones defectuosas",
            sustitucion: "Sustitución: Sistemas más seguros",
            controlesIngenieria: "Controles de ingeniería: Protecciones eléctricas",
            controlesAdministrativos: "Controles administrativos: Capacitación"
        }
    },

    "Electricidad estática": {
        consecuencias: "Quemaduras fibrilación ventricular shock eléctrico",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: false,
            EMOMP: false,
            EMOA: true,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: true,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: true,
            CH: true,
            PL: false,
            PAS:false,
            PE: false,
            PSP: true,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Calzado antiestático, muñequeras antiestáticas",
        medidasIntervencion: {
            eliminacion: "Eliminación: Control de humedad ambiental",
            sustitucion: "Sustitución: Materiales antiestáticos",
            controlesIngenieria: "Controles de ingeniería: Sistemas de puesta a tierra",
            controlesAdministrativos: "Controles administrativos: Procedimientos de control"
        }
    },






    "Iluminación deficiente": {
        consecuencias: "Fatiga visual generación de accidentes",
        peorConsecuencia: "Accidente grave",
        examenesMedicos: {
            EMO: false,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: true,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Lámparas portátiles, señalización fotoluminiscente",
        medidasIntervencion: {
            eliminacion: "Eliminación: Rediseño de iluminación",
            sustitucion: "Sustitución: Luminarias más eficientes",
            controlesIngenieria: "Controles de ingeniería: Sistemas automatizados",
            controlesAdministrativos: "Controles administrativos: Mantenimiento preventivo"
        }
    },

    "Iluminación en exceso": {
        consecuencias: "Fatiga visual generación de accidentes",
        peorConsecuencia: "Accidente grave",
        examenesMedicos: {
            EMO: false,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: true,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Gafas con filtro UV, cortinas o pantallas",
        medidasIntervencion: {
            eliminacion: "Eliminación: Rediseño de iluminación",
            sustitucion: "Sustitución: Sistemas regulables",
            controlesIngenieria: "Controles de ingeniería: Control automático",
            controlesAdministrativos: "Controles administrativos: Estudios de iluminación"
        }
    },

    "Presiones anormales": {
        consecuencias: "Heridas traumas abrasiones quemaduras",
        peorConsecuencia: "Daño severo",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Equipos de protección específicos, monitores de presión",
        medidasIntervencion: {
            eliminacion: "Eliminación: Cambio de proceso",
            sustitucion: "Sustitución: Equipos seguros",
            controlesIngenieria: "Controles de ingeniería: Sistemas de control",
            controlesAdministrativos: "Controles administrativos: Procedimientos específicos"
        }
    },

    "Radiaciones ionizantes": {
        consecuencias: "Enfermedades crónicas",
        peorConsecuencia: "Cáncer",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: true,
            VIS: true,
            ECG: true,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: true,
            PL: false,
            PAS:false,
            PE: true,
            PSP: false,
            TGO: true,
            TGP: true,
            TRI: false,
            CRE: true,
            BUN: true,
            T4L: true,
            TSH: true,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Dosímetros, delantales plomados, gafas plomadas",
        medidasIntervencion: {
            eliminacion: "Eliminación: Procesos alternativos",
            sustitucion: "Sustitución: Tecnologías más seguras",
            controlesIngenieria: "Controles de ingeniería: Blindaje",
            controlesAdministrativos: "Controles administrativos: Control de exposición"
        }
    },
    
    "Radiaciones no ionizantes": {
        consecuencias: "Lesiones menores hasta falla cardiopulmonar",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Gafas con filtro UV, ropa protectora UV",
        medidasIntervencion: {
            eliminacion: "Eliminación: Procesos alternativos",
            sustitucion: "Sustitución: Equipos más seguros",
            controlesIngenieria: "Controles de ingeniería: Apantallamiento",
            controlesAdministrativos: "Controles administrativos: Tiempo exposición"
        }
    },

    "Ruido": {
        consecuencias: "Hipoacusia alteraciones fisiológicas",
        peorConsecuencia: "Sordera permanente",
        examenesMedicos: {
            AUD: 1, // Crítico
            EMO: 2, // Recomendado
            ESP: 2,
            PSM: 2,
            PST: 2
        },
        elementosProteccion: "Protectores auditivos tipo copa, tapones auditivos",
        medidasIntervencion: {
            eliminacion: "Reemplazo de equipos",
            sustitucion: "Equipos más silenciosos",
            controlesIngenieria: "Encerramientos",
            controlesAdministrativos: "Tiempo exposición"
        }
    },

    "Temperaturas extremas: calor": {
        consecuencias: "Lesiones menores hasta falla cardiopulmonar",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Ropa térmica, sistemas de hidratación",
        medidasIntervencion: {
            eliminacion: "Eliminación: Automatización",
            sustitucion: "Sustitución: Procesos más frescos",
            controlesIngenieria: "Controles de ingeniería: Ventilación",
            controlesAdministrativos: "Controles administrativos: Pausas programadas"
        }
    },

    "Temperaturas extremas: frío": {
        consecuencias: "Congelamiento quemaduras",
        peorConsecuencia: "Hipotermia severa",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Ropa térmica, guantes térmicos, calzado térmico",
        medidasIntervencion: {
            eliminacion: "Eliminación: Automatización",
            sustitucion: "Sustitución: Procesos más templados",
            controlesIngenieria: "Controles de ingeniería: Calefacción",
            controlesAdministrativos: "Controles administrativos: Rotación personal"
        }
    },

    "Vibraciones mano-cuerpo": {
        consecuencias: "Enfermedades crónicas",
        peorConsecuencia: "Daño permanente",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: false,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Guantes anti-vibración, mangos ergonómicos",
        medidasIntervencion: {
            eliminacion: "Eliminación: Automatización",
            sustitucion: "Sustitución: Herramientas anti-vibración",
            controlesIngenieria: "Controles de ingeniería: Amortiguación",
            controlesAdministrativos: "Controles administrativos: Tiempo exposición"
        }
    },

    "Vibraciones cuerpo completo": {
        consecuencias: "Enfermedades crónicas",
        peorConsecuencia: "Daño permanente",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: false,
            ECG: false,
            RXC: true,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Asientos amortiguados, plataformas anti-vibración",
        medidasIntervencion: {
            eliminacion: "Eliminación: Automatización",
            sustitucion: "Sustitución: Equipos más modernos",
            controlesIngenieria: "Controles de ingeniería: Aislamiento",
            controlesAdministrativos: "Controles administrativos: Pausas"
        }
    },

    "Cambios bruscos de temperatura": {
        consecuencias: "Afecciones respiratorias de diversa magnitud, cefaleas.",
        peorConsecuencia: "Daño permanente",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: false,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Ropa térmica, guantes térmicos, calzado térmico",
        medidasIntervencion: {
            eliminacion: "Eliminación: Automatización",
            sustitucion: "Sustitución: Equipos más modernos",
            controlesIngenieria: "Controles de ingeniería: Aislamiento",
            controlesAdministrativos: "Controles administrativos: Pausas"
        }
    },

    "Humedad Relativa ( Vapor de agua)": {
        consecuencias: "En calor no puede bajar  temperatura corporal  correctament, cuando es baja, en ambientes fríos, causa un exceso de pérdidas de calor del cuerpo por evaporación de agua, provocando sequedad de la piel y de las mucosas",
        peorConsecuencia: "Daño permanente",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: false,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Dehumidificadores",
        medidasIntervencion: {
            eliminacion: "Eliminación: Automatización",
            sustitucion: "Sustitución: Equipos más modernos",
            controlesIngenieria: "Controles de ingeniería: Aislamiento",
            controlesAdministrativos: "Controles administrativos: Pausas"
        }
    },
    
    
    
    
    
    
    "Exposición a gases vapores humos polvos no tóxicos": {
        consecuencias: "Irritación respiratoria intoxicaciones alergias",
        peorConsecuencia: "Daño respiratorio",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Respiradores con filtros específicos, máscaras",
        medidasIntervencion: {
            eliminacion: "Eliminación: Procesos cerrados",
            sustitucion: "Sustitución: Productos menos tóxicos",
            controlesIngenieria: "Controles de ingeniería: Extracción",
            controlesAdministrativos: "Controles administrativos: Procedimientos"
        }
    },
    
    "Exposición a gases vapores humos polvos tóxicos": {
        consecuencias: "Irritación respiratoria intoxicaciones severas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: true,
            TGO: true,
            TGP: true,
            TRI: true,
            CRE: true,
            BUN: true,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: true,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Equipos de respiración autónoma, trajes químicos",
        medidasIntervencion: {
            eliminacion: "Eliminación: Cambio de proceso",
            sustitucion: "Sustitución: Productos no tóxicos",
            controlesIngenieria: "Controles de ingeniería: Sistemas cerrados",
            controlesAdministrativos: "Controles administrativos: Protocolos estrictos"
        }
    },

    "Exposición sustancias químicas líquidas tóxicas": {
        consecuencias: "Irritación intoxicación severa",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: true,
            TGO: true,
            TGP: true,
            TRI: true,
            CRE: true,
            BUN: true,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: true,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Trajes químicos, guantes químicos, botas químicas",
        medidasIntervencion: {
            eliminacion: "Eliminación: Procesos alternativos",
            sustitucion: "Sustitución: Productos no tóxicos",
            controlesIngenieria: "Controles de ingeniería: Sistemas cerrados",
            controlesAdministrativos: "Controles administrativos: Procedimientos especiales"
        }
    },

    "Exposición sustancias químicas líquidas no tóxicas": {
        consecuencias: "Irritación alergias leves",
        peorConsecuencia: "Reacción alérgica severa",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: true,
            TGO: true,
            TGP: true,
            TRI: true,
            CRE: true,
            BUN: true,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Guantes de nitrilo, gafas de seguridad",
        medidasIntervencion: {
            eliminacion: "Eliminación: Automatización",
            sustitucion: "Sustitución: Productos más seguros",
            controlesIngenieria: "Controles de ingeniería: Sistemas cerrados",
            controlesAdministrativos: "Controles administrativos: Procedimientos"
        }
    },

    "Exposición a sustancias químicas que generan efectos en el organismo": {
        consecuencias: "Anestesia cáncer y mutaciones",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: true,
            TGO: true,
            TGP: true,
            TRI: true,
            CRE: true,
            BUN: true,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: true,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Trajes especiales químicos, máscaras con filtros específicos, guantes de protección química",
        medidasIntervencion: {
            eliminacion: "Eliminación: Cambio de procesos productivos",
            sustitucion: "Sustitución: Uso de sustancias menos tóxicas",
            controlesIngenieria: "Controles de ingeniería: Sistemas cerrados automatizados",
            controlesAdministrativos: "Controles administrativos: Protocolos estrictos de manipulación"
        }
    },








    "Presencia de animales/vectores transmisores de enfermedad": {
        consecuencias: "Enfermedades crónicas dengue fiebre amarilla",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: true,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: true,
            TGP: true,
            TRI: false,
            CRE: true,
            BUN: true,
            T4L: false,
            TSH: false,
            BRU: true,
            PO: true,
            TOX: true,
            LEP: true,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Repelentes especiales, ropa manga larga, botas altas",
        medidasIntervencion: {
            eliminacion: "Eliminación: Control de plagas y vectores",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Barreras físicas y mallas",
            controlesAdministrativos: "Controles administrativos: Programas de fumigación"
        }
    },

    "Exposición a material contaminado o con riesgo biológico": {
        consecuencias: "Dermatopatías enfermedades infecciosas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: true,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: true,
            TGP: true,
            TRI: false,
            CRE: true,
            BUN: true,
            T4L: false,
            TSH: false,
            BRU: true,
            PO: true,
            TOX: true,
            LEP: true,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Guantes de nitrilo, mascarillas N95, trajes de bioseguridad",
        medidasIntervencion: {
            eliminacion: "Eliminación: Automatización de procesos con riesgo",
            sustitucion: "Sustitución: Uso de materiales estériles",
            controlesIngenieria: "Controles de ingeniería: Cabinas de bioseguridad",
            controlesAdministrativos: "Controles administrativos: Protocolos de bioseguridad"
        }
    },
    
    "Manipulación de alimentos": {
        consecuencias: "Enfermedades transmitidas por alimentos",
        peorConsecuencia: "Intoxicación severa",
        examenesMedicos: {
            EMOMP: 1, // Crítico/Obligatorio
            FRO: 1,   // Crítico/Obligatorio
            KOH: 1,   // Crítico/Obligatorio
            COP: 1,   // Crítico/Obligatorio
            VH: 2,    // Recomendado (VDRL/Serología)
            VT: 2     // Recomendado (Vértigo - menos común)
        },
        elementosProteccion: "Guantes de nitrilo, tapabocas, cofias, delantal",
        medidasIntervencion: {
            eliminacion: "Eliminación: Automatización de procesos",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Equipos de conservación",
            controlesAdministrativos: "Controles administrativos: BPM y HACCP"
        }
    },







    "Manejo de cargas mayores a 25 Kg (Hombres)": {
        consecuencias: "Lesiones osteomusculares",
        peorConsecuencia: "Lesión permanente",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: false,
            ECG: false,
            RXC: true,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Fajas ergonómicas, ayudas mecánicas, guantes de agarre",
        medidasIntervencion: {
            eliminacion: "Eliminación: Automatización de levantamiento",
            sustitucion: "Sustitución: Uso de ayudas mecánicas",
            controlesIngenieria: "Controles de ingeniería: Diseño de puestos",
            controlesAdministrativos: "Controles administrativos: Capacitación en manejo de cargas"
        }
    },

    "Manejo de cargas mayores a 12.5 Kg (Mujeres)": {
        consecuencias: "Lesiones osteomusculares",
        peorConsecuencia: "Lesión permanente",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: false,
            ECG: false,
            RXC: true,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Fajas ergonómicas, ayudas mecánicas, guantes de agarre",
        medidasIntervencion: {
            eliminacion: "Eliminación: Automatización de levantamiento",
            sustitucion: "Sustitución: Uso de ayudas mecánicas",
            controlesIngenieria: "Controles de ingeniería: Diseño ergonómico",
            controlesAdministrativos: "Controles administrativos: Límites de peso"
        }
    },

    "Adopción de posturas nocivas": {
        consecuencias: "Lesiones osteomusculares",
        peorConsecuencia: "Lesión permanente",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: true,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Sillas ergonómicas, reposapiés, pad mouse",
        medidasIntervencion: {
            eliminacion: "Eliminación: Rediseño de puestos",
            sustitucion: "Sustitución: Mobiliario ergonómico",
            controlesIngenieria: "Controles de ingeniería: Ajustes de altura",
            controlesAdministrativos: "Controles administrativos: Pausas activas"
        }
    },

    "Movimientos repetitivos (6 o más por minuto)": {
        consecuencias: "Lesiones osteomusculares",
        peorConsecuencia: "Lesión permanente",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: true,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Soportes ergonómicos, herramientas adaptadas",
        medidasIntervencion: {
            eliminacion: "Eliminación: Automatización de tareas",
            sustitucion: "Sustitución: Herramientas ergonómicas",
            controlesIngenieria: "Controles de ingeniería: Ayudas mecánicas",
            controlesAdministrativos: "Controles administrativos: Rotación de tareas"
        }
    },

    "Diseño del puesto de trabajo inadecuado": {
        consecuencias: "Lesiones osteomusculares",
        peorConsecuencia: "Lesión permanente",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: true,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Mobiliario ergonómico, soportes ajustables",
        medidasIntervencion: {
            eliminacion: "Eliminación: Rediseño completo",
            sustitucion: "Sustitución: Mobiliario adaptable",
            controlesIngenieria: "Controles de ingeniería: Ajustes personalizados",
            controlesAdministrativos: "Controles administrativos: Evaluaciones ergonómicas"
        }
    },
    
    "Posturas prolongadas y/o incorrectas": {
        consecuencias: "Lesiones osteomusculares",
        peorConsecuencia: "Lesión permanente",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: true,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Mobiliario ergonómico, soportes ajustables",
        medidasIntervencion: {
            eliminacion: "Eliminación: Jornadas sin pausas activas",
            sustitucion: "Sustitución: Mobiliario adaptable",
            controlesIngenieria: "Controles de ingeniería: Ajustes personalizados",
            controlesAdministrativos: "Controles administrativos: evaluacion pausas activas"
        }
    },







    "Competencias no definidas para el cargo": {
        consecuencias: "Incidentes de trabajo",
        peorConsecuencia: "Accidente grave",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: false,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "No aplica EPP - Requiere controles administrativos",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: No aplica",
            controlesAdministrativos: "Controles administrativos: Perfiles de cargo definidos"
        }
    },

    "Actos inseguros observados": {
        consecuencias: "Incidentes y enfermedades",
        peorConsecuencia: "Accidente fatal",
        examenesMedicos: {
            EMO: false,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: false,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "EPP según la tarea específica",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Sistemas a prueba de error",
            controlesAdministrativos: "Controles administrativos: Programa de comportamiento seguro"
        }
    },








    "Atención de público": {
        consecuencias: "Estrés irritabilidad ansiedad",
        peorConsecuencia: "Burnout",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: false,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "No aplica EPP - Requiere controles administrativos",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Barreras físicas",
            controlesAdministrativos: "Controles administrativos: Pausas programadas"
        }
    },

    "Monotonía/repetitividad de funciones": {
        consecuencias: "Estrés desmotivación",
        peorConsecuencia: "Burnout",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: false,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "No aplica EPP - Requiere controles administrativos",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: Automatización parcial",
            controlesIngenieria: "Controles de ingeniería: No aplica",
            controlesAdministrativos: "Controles administrativos: Rotación de tareas"
        }
    },

    "Trabajo bajo presión": {
        consecuencias: "Estrés ansiedad irritabilidad",
        peorConsecuencia: "Burnout",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: false,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "No aplica EPP - Requiere controles administrativos",
        medidasIntervencion: {
            eliminacion: "Eliminación: Reorganización de procesos",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: No aplica",
            controlesAdministrativos: "Controles administrativos: Gestión del tiempo"
        }
    },







    "Almacenamiento inadecuado": {
        consecuencias: "Golpes contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: false,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Casco, calzado de seguridad, guantes",
        medidasIntervencion: {
            eliminacion: "Eliminación: Rediseño de almacenamiento",
            sustitucion: "Sustitución: Sistemas automatizados",
            controlesIngenieria: "Controles de ingeniería: Estanterías seguras",
            controlesAdministrativos: "Controles administrativos: Procedimientos de almacenamiento"
        }
    },

    "Condiciones inadecuadas de orden y aseo": {
        consecuencias: "Caídas golpes contusiones",
        peorConsecuencia: "Lesión grave",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Calzado antideslizante, guantes de protección",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Sistemas de almacenamiento",
            controlesAdministrativos: "Controles administrativos: Programa 5S"
        }
    },

    "Condiciones del piso": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Calzado antideslizante, señalización de áreas",
        medidasIntervencion: {
            eliminacion: "Eliminación: Reemplazo de pisos deteriorados",
            sustitucion: "Sustitución: Materiales antideslizantes",
            controlesIngenieria: "Controles de ingeniería: Tratamientos superficiales",
            controlesAdministrativos: "Controles administrativos: Inspecciones periódicas"
        }
    },

    "Escaleras y barandas inadecuadas o mal estado": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Calzado antideslizante, señalización",
        medidasIntervencion: {
            eliminacion: "Eliminación: Reemplazo de estructuras",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Muros de contención",
            controlesAdministrativos: "Controles administrativos: Plan de emergencias"
        }
    },

    "Condiciones de las instalaciones": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Casco, calzado de seguridad",
        medidasIntervencion: {
            eliminacion: "Eliminación: Renovación de instalaciones",
            sustitucion: "Sustitución: Mejora de infraestructura",
            controlesIngenieria: "Controles de ingeniería: Reforzamiento estructural",
            controlesAdministrativos: "Controles administrativos: Inspecciones programadas"
        }
    },











    "Deslizamientos": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Botas impermeables, chalecos salvavidas",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Sistemas de drenaje",
            controlesAdministrativos: "Controles administrativos: Plan de emergencias"
        }
    },

    "Inundación": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Botas impermeables, chalecos salvavidas",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Sistemas de drenaje",
            controlesAdministrativos: "Controles administrativos: Plan de emergencias"
        }
    },

    "Sismo - Terremotos": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Casco, kit de emergencias",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Refuerzo estructural",
            controlesAdministrativos: "Controles administrativos: Plan de evacuación"
        }
    },

    "Tormentas eléctricas": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Equipo de protección para rayos, pararrayos",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Sistemas pararrayos",
            controlesAdministrativos: "Controles administrativos: Protocolos tormenta"
        }
    },

    "Lluvias granizadas": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Impermeables, botas de agua",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Techos reforzados ",
            controlesAdministrativos: "Controles administrativos: Procedimientos climáticos"
        }
    },












    "Secuestros": {
        consecuencias: "Pérdida libertad traumas psicológicos",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Sistemas de comunicación, GPS",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Sistemas de rastreo",
            controlesAdministrativos: "Controles administrativos: Protocolos anti-secuestro"
        }
    },

    "Amenazas": {
        consecuencias: "Cuadros depresivos ansiedad suicidios",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Sistemas de comunicación, alarmas",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Sistemas de seguridad",
            controlesAdministrativos: "Controles administrativos: Protocolos de protección"
        }
    },

    "Hurtos - Robos - Atracos": {
        consecuencias: "Pérdida económica depresión trauma",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Sistemas de alarma, CCTV",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Control acceso",
            controlesAdministrativos: "Controles administrativos: Protocolos seguridad"
        }
    },

    "Accidente de Tránsito": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: true,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Cinturón seguridad, kit carretera",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Mantenimiento vehicular",
            controlesAdministrativos: "Controles administrativos: Plan seguridad vial"
        }
    },
    
    "Desorden público - Atentados": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Elementos de comunicación, rutas escape",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Refugios seguros",
            controlesAdministrativos: "Controles administrativos: Plan contingencia"
        }
    },
    
    "Extorsión": {
        consecuencias: "Pérdida económica alteración nerviosa",
        peorConsecuencia: "Trauma psicológico",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: false,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Sistemas comunicación segura",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Sistemas anti-rastreo",
            controlesAdministrativos: "Controles administrativos: Protocolos anti-extorsión"
        }
    },








    "Trabajos en caliente": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: true,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: true,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Careta soldador, guantes especiales, ropa ignífuga",
        medidasIntervencion: {
            eliminacion: "Eliminación: Procesos alternativos",
            sustitucion: "Sustitución: Métodos más seguros",
            controlesIngenieria: "Controles de ingeniería: Ventilación forzada",
            controlesAdministrativos: "Controles administrativos: Permisos trabajo"
        }
    },

    "Explosión": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "EPP específico según riesgo explosivo",
        medidasIntervencion: {
            eliminacion: "Eliminación: Procesos alternativos",
            sustitucion: "Sustitución: Materiales menos peligrosos",
            controlesIngenieria: "Controles de ingeniería: Sistemas anti-explosión",
            controlesAdministrativos: "Controles administrativos: Procedimientos ATEX"
        }
    },
    
    "Incendio": {
        consecuencias: "Heridas traumas contusiones fracturas",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Trajes contra incendios, equipos autocontenidos",
        medidasIntervencion: {
            eliminacion: "Eliminación: Materiales no combustibles",
            sustitucion: "Sustitución: Materiales retardantes",
            controlesIngenieria: "Controles de ingeniería: Sistemas contraincendios",
            controlesAdministrativos: "Controles administrativos: Plan emergencia"
        }
    },
    










    
    "Sin disponibilidad de agua potable": {
        consecuencias: "Enfermedades gastrointestinales",
        peorConsecuencia: "Deshidratación severa",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: false,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: true,
            TOX: false,
            LEP: false,
            COP: true,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "Filtros de agua, contenedores seguros",
        medidasIntervencion: {
            eliminacion: "Eliminación: Conexión acueducto",
            sustitucion: "Sustitución: Fuentes alternativas",
            controlesIngenieria: "Controles de ingeniería: Sistemas purificación",
            controlesAdministrativos: "Controles administrativos: Control calidad agua"
        }
    },









    "Enfermedades endémicas": {
        consecuencias: "Enfermedades de diferente tipo",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: false,
            GLI: false,
            CH: false,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: false,
            TGP: false,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: false,
            PO: false,
            TOX: false,
            LEP: false,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: false,
            VT: false,
            VFA: false
        },
        elementosProteccion: "EPP bioseguridad, tapabocas N95",
        medidasIntervencion: {
            eliminacion: "Eliminación: No aplica",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Ventilación",
            controlesAdministrativos: "Controles administrativos: Protocolos sanitarios"
        }
    },

    "Mordedura y Picadura de Animales": {
        consecuencias: "Reacciones alérgicas shock anafiláctico",
        peorConsecuencia: "Muerte",
        examenesMedicos: {
            EMO: true,
            EMOMP: false,
            EMOA: false,
            AUD: true,
            ESP: true,
            OPT: false,
            VIS: true,
            ECG: false,
            RXC: false,
            PSM: false,
            PST: true,
            GLI: false,
            CH: true,
            PL: false,
            PAS:false,
            PE: false,
            PSP: false,
            TGO: true,
            TGP: true,
            TRI: false,
            CRE: false,
            BUN: false,
            T4L: false,
            TSH: false,
            BRU: true,
            PO: false,
            TOX: true,
            LEP: true,
            COP: false,
            FRO: false,
            KOH: false,
            COLI: false,
            VH: true,
            VT: true,
            VFA: true
        },
        elementosProteccion: "Ropa protectora, repelentes",
        medidasIntervencion: {
            eliminacion: "Eliminación: Control de plagas",
            sustitucion: "Sustitución: No aplica",
            controlesIngenieria: "Controles de ingeniería: Barreras físicas",
            controlesAdministrativos: "Controles administrativos: Protocolos primeros auxilios"
        }
    },
    // ... otros GES
};