name: Build and Deploy Frontend
on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: npm install --prefix client

      - name: Build Frontend Project
        run: npm run build --prefix client

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            rsync -avzr --delete /github/workspace/dist/ /var/www/html/ 