name: Deploy Backend
on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy and Restart Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /var/www/genesys-project
            git pull
            npm install --prefix server --omit=dev
            pm2 reload backend-api 